ALTER TABLE members ADD COLUMN draft TEXT;
ALTER TABLE members ADD COLUMN draft_at INTEGER DEFAULT 0;
ALTER TABLE vaults ADD COLUMN draft TEXT;
ALTER TABLE vaults ADD COLUMN draft_at INTEGER DEFAULT 0;
CREATE TABLE IF NOT EXISTS bans (
  room TEXT NOT NULL,
  username TEXT NOT NULL,
  PRIMARY KEY (room, username)
);